inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
