inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/NestedGroups:
  Max: 4

Style/EmptyMethod:
  EnforcedStyle: expanded
