inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
  TargetRubyVersion: 2.4

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/EmptyMethod:
  EnforcedStyle: expanded
