version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: expiration_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - expiration-{{ checksum "Gemfile.lock" }}
            - expiration-
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: sudo apt install -y postgresql-client || true
      - save_cache:
          key: expiration-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Database Setup
          command: bundle exec rails db:create db:schema:load db:migrate
      - run:
          name: Tests
          command: bundle exec rspec spec --format progress
  rubocop:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - expiration-{{ checksum "Gemfile.lock" }}
            - expiration-
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: expiration-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Assure no violations
          command: bundle exec rubocop --config .rubocop.yml --fail-level refactor
workflows:
  version: 2
  build:
    jobs:
      - test
      - rubocop
