default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: expiration

development:
  <<: *default
  database: expiration_development

test:
  <<: *default
  database: expiration_test

production:
  <<: *default
  database: expiration_production
  password: <%= ENV['EXPIRATION_DATABASE_PASSWORD'] %>
